apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wordpress
  namespace: openshift-gitops
spec:
  destination:
    namespace: wordpress
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      recurse: true
    path: wordpress
    repoURL: https://github.com/arthur-r-oliveira/argocd-example-apps-wordpress.git
    targetRevision: main
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true